### ISSUE TITLE
About precalculated tables

### ISSUE THREAD

**Issue by Benjap700** [borenstein-lab/robustness#1]
Your method have shown really interesting results, but in order to improve the quality of results and conclusions, I would like to ask you a couple of questions:

1) Your software uses some precalculated tables, some of them from PICRUSt. Now exist a new version of this software, PICRUSt2, that use a diferent dataset that can not be used directly in your scripts. The question is if you know the way for use an actualized dataset or this purpose is not possible without rewriting those scripts.

2) The second question is whether using these available precalculated tables can lead to significant errors in the estimation of Attenuation and Buffering or, conversely, whether the results obtained are currently acceptable. What is your opinion?

Best wishes and congratulations for your excellent work

**Comment by engal** [comment]
Glad to hear you're interested in our work! Regarding your questions:

1. I haven't had a chance to test this, but theoretically you should be able to substitute the base data files with output files from PICRUSt2. Specifically, PICRUSt2 generates:
- a `marker_nsti_predicted.tsv.gz` file, which should replace the 16S copy number table
- a `KO_predicted.tsv.gz` file, which should replace the genomic content annotation table
- an `out.tre` file, which should replace the phylogenetic tree.
There may be some issues with table/tree formatting, but that data should work. If you are in a hurry, you can try doing the one-to-one file replacement and see if it works, but I should have some time to test this out this week and can get back to you with the results.

2. I think using the precalculated tables with Greengenes-annotated taxonomic data can provide informative and useful results, but using PICRUSt2-based data should improve sensitivity since you should be able to use more of the ASV data (rather than collapsing everything to the more limited Greengenes tree) and the more up-to-date data should improve accuracy of results.

I hope that answers your questions, and I'll try out the replacement PICRUSt2 tables and get back to you.

**Comment by Benjap700** [comment]
Thanks for your quick answers and help, Alex
Your offer to try get the tables is very kind, please inform me if you get it. However, if you have little time or are too busy these days do not hesitate to say so and we will try.
Best regards!

**Comment by engal** [comment]
Good news!

It looks like PICRUSt2 output files can be used with this software. I had to slightly update one of the scripts to allow this, so you'll need to clone/pull from the current version of the repository to get that change.

Some quick notes on how to make use of your PICRUSt2 output files:

1. When running the `generate_perturbations.R` script, you'll need to use the following options to point to your PICRUSt2 output files, rather than the precalculated files that are used by default: `--genome_content_table <path_to_PICRUSt2_KO_predictions_table> --copy_number_norm_table <path_to_PICRUSt2_16S_predctions_table> --tree <path_to_PICRUSt2_read_placement_tree>`
2. When running the `summarize_perturbations.R` script, you'll also need to use the following option to make sure you're using the same PICRUSt2 output file: `--genome_content_table <path_to_PICRUSt2_KO_predictions_table>`

Please let me know if this works for you, or if you run into any issues.

**Comment by Benjap700** [comment]
Thanks for your answer and, specially, for your effort.
I suppose I have to get PICRUSt2 files for every sample, is it correct?

**Comment by engal** [comment]
You should be able to generate general files that can be shared across multiple samples. The required PICRUSt2 output files only depend on the sequence placement and hidden-state prediction steps in the PICRUSt2 pipeline, which do not require any sample-specific data. Instead, these steps only rely on the representative sequences for your ASVs. Thus, you can pool any ASV sequences you are interested in (they don't necessarily need to come from the same sample) and run the first two steps in the PICRUSt2 pipeline on those sequences. This will generate a predicted genomic content file, a predicted 16S copy number file, and a tree that can be used by our software for any sample that consists of ASVs present in the input you gave to PICRUSt2.

I hope that all makes sense.

**Comment by Benjap700** [comment]
The pipeline worked perfectly taking in account your instructions. Thanks for your help!
Best regards
Benjamí

**Comment by engal** [comment]
Glad I could help!
